export enum FacebookMessageWebhookEvent {
  MESSAGE_DELIVERIES = "message_deliveries",
  MESSAGE_ECHOES = "message_echoes",
  MESSAGE_EDITS = "message_edits",
  MESSAGE_REACTIONS = "message_reactions",
  MESSAGE_READS = "message_reads",
  MESSAGES = "messages",
  MESSAGING_ACCOUNT_LINKING = "messaging_account_linking",
  MESSAGING_FEEDBACK = "messaging_feedback",
  MESSAGING_GAME_PLAYS = "messaging_game_plays",
  MESSAGING_HANDOVERS = "messaging_handovers",
  MESSAGING_OPTINS = "messaging_optins",
  MESSAGING_POLICY_ENFORCEMENT = "messaging_policy_enforcement",
  MESSAGING_POSTBACKS = "messaging_postbacks",
  MESSAGING_REFERRALS = "messaging_referrals",
  MESSAGING_SEEN = "messaging_seen",
  RESPONSE_FEEDBACK = "response_feedback",
  SEND_CART = "send_cart",
  STANDBY = "standby",
}
