export enum ConversationApiErrorMessage {
  REQUEST_BODY_CREATION_FAILED = "REQUEST_BODY_CREATION_FAILED",
  PASS_THREAD_CONTROL_FAILED = "PASS_THREAD_CONTROL_FAILED",
  PARSE_PASS_THREAD_CONTROL_RESPONSE_FAILED = "PARSE_PASS_THREAD_CONTROL_RESPONSE_FAILED",
  TAKE_THREAD_CONTROL_FAILED = "TAKE_THREAD_CONTROL_FAILED",
  PARSE_TAKE_THREAD_CONTROL_RESPONSE_FAILED = "PARSE_TAKE_THREAD_CONTROL_RESPONSE_FAILED",
  REQUEST_THREAD_CONTROL_FAILED = "REQUEST_THREAD_CONTROL_FAILED",
  PARSE_REQUEST_THREAD_CONTROL_RESPONSE_FAILED = "PARSE_REQUEST_THREAD_CONTROL_RESPONSE_FAILED",
  GET_THREAD_OWNER_FAILED = "GET_THREAD_OWNER_FAILED",
  PARSE_THREAD_OWNER_RESPONSE_FAILED = "PARSE_THREAD_OWNER_RESPONSE_FAILED",
  GET_SECONDARY_RECEIVERS_FAILED = "GET_SECONDARY_RECEIVERS_FAILED",
  PARSE_SECONDARY_RECEIVERS_RESPONSE_FAILED = "PARSE_SECONDARY_RECEIVERS_RESPONSE_FAILED",
}
