export enum FacebookOAuthErrorMessage {
  TOKEN_REQUEST_VALIDATION_FAILED = "TOKEN_REQUEST_VALIDATION_FAILED",
  TOKEN_REQUEST_FAILED = "TOKEN_REQUEST_FAILED",
  TOKEN_RESPONSE_VALIDATION_FAILED = "TOKEN_RESPONSE_VALIDATION_FAILED",
  GRAPH_API_ERROR = "GRAPH_API_ERROR",
  ACCESS_TOKEN_MISSING = "ACCESS_TOKEN_MISSING",
}
