export enum MessagingErrorMessage {
  SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED",
  PARSE_MESSAGE_RESPONSE_FAILED = "PARSE_MESSAGE_RESPONSE_FAILED",
  MISSING_IMAGE_URL = "MISSING_IMAGE_URL",
  TOO_MANY_IMAGES = "TOO_MANY_IMAGES",
}
