export enum WebhookErrorMessage {
  FETCH_PAGE_DETAILS_FAILED = "FETCH_PAGE_DETAILS_FAILED",
  PARSE_PAGE_DETAILS_RESPONSE_FAILED = "PARSE_PAGE_DETAILS_RESPONSE_FAILED",
  SUBSCRIBE_WEBHOOKS_FAILED = "SUBSCRIBE_WEBHOOKS_FAILED",
  PARSE_WEBHOOK_SUBSCRIPTION_RESPONSE_FAILED = "PARSE_WEBHOOK_SUBSCRIPTION_RESPONSE_FAILED",
  GET_SUBSCRIBED_APPS_FAILED = "GET_SUBSCRIBED_APPS_FAILED",
  PARSE_SUBSCRIBED_APPS_RESPONSE_FAILED = "PARSE_SUBSCRIBED_APPS_RESPONSE_FAILED",
}
